@name = gui
@email = gui@test.com
@password = test1234

# @name register
POST http://localhost:3333/register HTTP/1.1
content-type: application/json

{
  "name":"{{name}}",
  "email": "{{email}}",
  "password": "{{password}}"
}
###
#  @name login
POST http://localhost:3333/login HTTP/1.1
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}
###

# @name ProffyRegister
POST http://localhost:3333/classes HTTP/1.1
content-type: application/json

{
  "userId":"{{login.response.body.user.id}}",
  "name":"teste proffy",
  "avatar":"aefga",
  "whatsapp":"asefa",
  "bio":"asef",
  "isProffy":false,
  "subject":"Matemática",
  "cost":80,
  "schedule":[
    { "week_day":1, "from": 8,"to":12},
    { "week_day":3, "from":10,"to":18},
    { "week_day":4, "from": 9,"to":11}
  ]
}
###

# @name ProfileUpdate
PUT http://localhost:3333/classes HTTP/1.1
content-type: application/json

{
  "userId":"95f7adfd-a6f9-44c8-ac2a-55916a0ecfb8",
  "name":"Pedro Proffy",
  "avatar":"aefga",
  "whatsapp":"asefa",
  "bio":"asef",
  "isProffy":true,
  "subject":"Matemática",
  "cost":80,
  "schedule":[
    { "week_day":5, "from": 8,"to":12},
    { "week_day":3, "from":10,"to":18},
    { "week_day":4, "from": 9,"to":11}
  ]
}